\documentclass[12pt]{article}
\usepackage{color}
\usepackage{cite}
\usepackage{geometry}                % See geometry.pdf to learn the layout options. There are lots.
%\usepackage{pdflscape}        %single page landscape
                                %mode \begin{landscape} \end{landscape}
\geometry{letterpaper}                   % ... or a4paper or a5paper or ... 
%\usepackage[parfill]{parskip}    % Activate to begin paragraphs with an empty line rather than an indent
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{/Library/Frameworks/R.framework/Resources/share/texmf/Sweave}


\title{Facilitation Alters the Structure of Covariances among Alpine
  Plant Species}
\author{M.K. Lau}
%\date{}                                           % Activate to display a given date or no date

\begin{document}
\maketitle


\setcounter{tocdepth}{3}
\tableofcontents

\section{Summary}
\begin{itemize}
\item Question: Does phylogenetic history predict the effect of
  alpine cushion species on the interactions among associated species?
\item Approach: 
  \begin{enumerate}
  \item Using a world-wide alpine plant database, generate
  covariance based models of interactions among other plant species.
  \item Identify 
  \end{enumerate}
\item Modeling: 
  \begin{enumerate}
  \item Partial correlations are generated using a distance based
    metric of correlation
  \end{enumerate}
\end{itemize}

\section{Introduction}
\begin{itemize}
\item Interactions contribute to the evolution and distribution of
  biological diversity.
\item Ecological systems theory suggests that it is important to
  consider interactions in greater complexity than just single
  pairwise studies.
\item Recent advances in ecological modeling have introduced methods
  from informatics to resolve and analyze complex ecological networks.
\item Plant-plant interactions are particularly important as they form
  the base of trophic networks and structure entire ecosystems through
  bottom-up forces.
\item Previous work has shown that plant-plant interactions are likely
  to be structured by phylogenetic contraints, suggesting underlying
  ecological forces that have shaped the evolution of interactions
  among species (Brad's phylo paper).
\item Here, we investigate how both local ecological and phylogenetics
  predict the outcome of interactions among species using a world-wide
  dataset of plant-plant co-occurrences and community network modeling
  and analytics.
\item We show that:
  \begin{enumerate}
  \item The structure of species covariances is strongly determined by
    compositional shifts from facilitation
  \item These structural differences are also predicted by
    phylogenetic relatedness 
  \end{enumerate}
\item These results suggest that evolutionary history is a strong
  determinant of complex, local interactions between species and that
  this occurs largely through a compositional filtering of species.
\end{itemize}

\section{Methods}

\subsection{Methods Stolen from SEM paper}
METHODS
Study Sites 
Data were collected from 78 alpine plant communities in North and
South America, Europe, Asia and New Zealand. Sites were selected to
include sufficiently large populations of cushion plants, which were
located in generally low productivity habitats within alpine belts
(i.e. above natural tree line). Forty eudicot cushion plant species
were sampled across the 78 sites (see Supplementary Information).

Sampling 
At each site we haphazardly selected a number of individual cushions
(see Supplementary Information for details of sample size at each
site) and all plants growing within these selected cushions were
identified to species level and recorded. Since cushions are usually
of elliptical form, we measured the maximum and minimum axes of each
cushion to estimate its area. To obtain comparable samples of species
richness in surrounding open areas, the size and shape of each sampled
cushion was emulated on haphazardly selected points in open areas away
from cushions and all plant individuals within these selected points
in open areas were identified to species level and recorded. Further,
the percentage cover of cushions and open areas was determined at each
site with 50 m long linear transects. We sampled a mean (±1 SE) of 81
(±3) sets of paired plots per cushion species and site. 

Climatic Data
For each site, estimates of the following monthly meteorological
conditions were extracted from the archive of the Global Land Data
Assimilation System (GLDAS): near-surface minimum, maximum, and mean
air temperature, near-surface relative humidity, precipitation and
actual evapotranspiration. GLDAS is a global, high-resolution, offline
terrestrial modeling system that merges satellite and ground-based
observations to produce optimal estimates of land surface states and
fluxes1. GLDAS meteorological fields are a merged product of
lapse-rate corrected Global Data Assimilation System (GDAS)
atmospheric conditions2, NOAA Climate Prediction Center (CPC)
operational global Merged Analysis of Precipitation (CMAP)3, and the
Air Force Weather Agency’s (AFWA) Agricultural Meteorology modeling
system (AGRMET)4. The GLDAS modeling system includes a suite of land
surface models implemented at various spatial resolutions. In this
application, data were drawn from the GLDAS 25km, Noah Land Surface
Model5-7 simulations for the period 2001-2010.
Monthly vegetation indices were drawn from the Moderate Imaging
Spectrometer (MODIS) 0.05° resolution normalized difference vegetation
index (NDVI) product (MOD13C2)8 for the period 2001-2010. NDVI is
commonly used as an indicator of vegetation cover and/or health. No
further processing of MOD13C2 was performed in this study.

Data analyses 
Interactions
We estimate the relative interaction intensity (RII) for each species
in the community as RII = (# in cushion – # in open)/(# in cushion + #
in open). Mean RII across all species within a community was used as
an estimate of the average cushion effect at that site. It is
important to note that RII measured the effect of cushion on species
abundance.

Cushion effect on total species richness
Assessing the effects of facilitation on species richness at the
entire community level relies on comparing the number of species that
a community has because of the presence of nurses to the richness
expected in the community without nurses (Cavieres & Badano 2009). To
estimate species richness for the community with cushions, we
generated synthetic datasets combining data of cushions and open areas
in a single species x samples matrix for each study site and a
rarefaction analysis was run for each site. Since our sampling
protocol included samples of different areas we used sample-based
rarefaction techniques to avoid biases due to the sequence in which
samples were added to the curves. On each rarefaction, 500 resamples
were randomly drawn with replacement for each sample size (from 1
sample to the maximum number of samples) and the Mau-Tao estimator of
species richness (Colwell et al. 2004) at the asymptote was
calculated. The expected species richness of the community without
cushions was estimated from the asymptotes of rarefaction curves
constructed using only open areas samples (Badano et al. 2006). To
assess the magnitude of the increase in species richness at the
community level due to the presence of cushions, we calculated the
proportion of increase in species richness as: (Stotal – Sopen) /
Stotal, where Stotal is the actual number of species in the community,
including the species growing both within and outside nurses; while
Sopen is the number of species in the absence of nurses (i.e. open
areas). All rarefaction analyses were performed with the software
EstimateS v. 8 (Colwell 2006).



\section{Dependencies and R Meta}
<<echo=false,results=hide>>=
  ##Originally written in R 12.2.1
  library(bipartite)
library(xtable)
library(gplots)
library(sna)
library(sem)
library(OpenMx)
library(GeneNet)
source('/Users/Aeolus/Documents/Active_Projects/GeneticNetworks/Genetic_Networks/ind_net.R')
source('/Users/Aeolus/Documents/Active_Projects/CorNets/CorNets.R')
source('/Users/Aeolus/Documents/Active_Projects/New_Functions/New_Functions.R')
if (any(ls() == 'panel.cor')){}else{
  example(pairs,echo=FALSE,verbose=FALSE,ask=FALSE)
}

@

%%%%Investigation of the Magwene-Dyer-Nasson Method of Network Independence
<<echo=false,results=hide>>=
fowl <- read.csv('/Users/Aeolus/Desktop/Dunn\ Fowl\ Data.csv')
exc <- fowl[,ncol(fowl)]
                                        #fowl <- fowl[exc != 'EXCLUDE',]
fowl <- fowl[,-ncol(fowl)]
fowl <- na.omit(fowl)
fowl <- as.matrix(fowl)
fowl <- fowl[,c(1,2,5,6,3,4)]
N <- nrow(fowl)
S <- cov(fowl)
p_ij<- solve(S)
R <- cor(fowl)
r_ij <- p_ij*0
for (i in 1:nrow(p_ij)){
  for (j in 1:ncol(p_ij)){
    r_ij[i,j] <- (-p_ij[i,j])/sqrt(p_ij[i,i]*p_ij[j,j])
  }
}
inet <- r_ij
eed <- -N*log((1-r_ij^2),base=exp(1))
diag(eed) <- 0
inet[eed < 3.84] <- 0
                                        #using my ind.net function
com <- apply(fowl,2,function(x) x/sum(x))
bc.inet <- ind.net(vegdist(t(com)),nrow(com))
rownames(bc.inet) <- colnames(bc.inet) <- colnames(com)
heatmap(abs(inet-bc.inet))
par(mfrow=c(2,2))
image((inet))
image((bc.inet))
gplot(abs(inet),displaylabels=TRUE,gmode='graph',edge.lwd=abs(inet)*10)
gplot(abs(bc.inet),displaylabels=TRUE,gmode='graph',edge.lwd=abs(bc.inet)*10)


@ 


\section{Description of Datasets}

\subsection{Brad's Phylo Stats}

\begin{itemize}
\item Number of paired plots
\item Species richness
\item Mean z-score of net relatedness index with all plots pooled
  (cushion and open). The z-score is based on comparison with an
  independent swap null model (see Picante R library >  ses.mpd
  function for details, and Gotelli 2000 Ecology).  NRI is -1*MPD,
  where MPD is mean pairwise (phylogenetic) distance among all species
  within a plot (see Swenson et al. 2006 Ecology)
\item Standard error of above (sample size=2n)
\item Mean z-score of NRI in cushions only. The species pool for the
  null model includes all species in the community, even if they do
  not occur in cushions.
\item Standard error of above
\item Mean z-score of NRI in open only.
\item Standard error of above
\item Mean pairwise distance separating taxa in paired cushion and
  open plots, a measure of phylobetadiversity. This can be compared to
  the phylobetadiversity across cushions and across open plots (see
  below) to estimate the relative phylogenetic turnover between versus
  within microhabitat types (i.e., there is no null model that this is
  compared to)
\item Standard error of above
\item MPD across cushions
\item Standard error of above
\item MPD across open plots. #VALUE indicates insufficient number of
  species to calculate the index
\item Standard error of above
\item Other Data:
  \subitem Test of phylogenetic signal in microhabitat preference,
  Blomberg's K; there is rarely enough statistical power for this
  test, due to the relatively small number of species, but when
  phylogenetic signal is significant it is one of divergence
  (i.e. close relatives have different microhabitat preferences); see
  phylosignal function in picante
  \subitem Several phylogenetic diversity indices (see Picante)
\end{itemize}


\section{Import Data}
%%%Data were provided by the Apling Pals Group with permission from
%%%Ray Callaway and others. Robbin Brooker provided the access to the
%%%data. Brad Butterfield provided .csv files that he had
%%%updated. Brad Cook helped to facilitate data acquisition.

<<echo=false,results=hide>>=
  if (any(ls() == 'cush.data')){load.data <- TRUE}else{load.data <- FALSE}
setwd('~/Documents/Active_Projects/FacilitationNetworks/GeneticsofFacilitationNetworks/')
if (any(ls() == 'run.models')){}else{run.models <- TRUE}

@ 

<<results=hide>>=
  if (load.data == TRUE){
    if (any(ls() == 'mywd')){}else{mywd <- getwd()}
    setwd('data')
    cush.data <- list()
    for (i in 1:length(dir())){
      cush.data[[i]] <- read.csv(dir()[i])
    }
    names(cush.data) <- paste(lapply(cush.data,function(x) colnames(x)[2]),dir(),sep='_')
    cush.site <- substr(dir(),1,7)
    cush.site <- unlist(lapply(strsplit(cush.site,split='\\.'),function(x) x[1]))
    setwd(mywd)
    ##Check the data quality and fix problems
    ##Find datasets with cushion.open labels that are different from the majority of labels
    ##NOTE: datasets Site9, Site46 and Site72 all had spelling errors in the cushion.open columns.
    ##These were fixed in the datasheets.
    as.character(unique(unlist(lapply(cush.data,function(x) x[,4]))))
    ##Change NA to 0
    for (i in 1:length(cush.data)){
      cush.data[[i]][is.na(cush.data[[i]])] <- 0
    }
    ##Remove species with less than qn abundance
    qn <- 10
    cush.data <- lapply(cush.data,function(x) data.frame(x[,1:4],rm.spp(x[,5:ncol(x)],n=qn)))
                                        #isolate the community data
    cush.com <- lapply(cush.data,function(x) x[,5:ncol(x)])
                                        #remove NA values
    cush.com <- lapply(cush.com,na.omit)
                                        #isolate the rep data
    cush.rep <- lapply(cush.data,function(x) x[,3])
                                        #isolate the microsiate data
    cush.micro <- lapply(cush.data,function(x) x[,4])
  }else{}

@ 

\section{Abundance Differences Produced by Cushions}

<<>>=
##Use a paired test of the differences in abundances
cush.a <- list()
cush.ap <- list()
for (i in 1:length(cush.com)){
  xc <- apply(cush.com[[i]][cush.micro[[i]] == 'cushion',],1,sum)
  xo <- apply(cush.com[[i]][cush.micro[[i]] == 'open',],1,sum)
  yc <- cush.rep[[i]][cush.micro[[i]] == 'cushion']
  yo <- cush.rep[[i]][cush.micro[[i]] == 'open']  
  xc <- xc[order(yc)];  yc <- yc[order(yc)]
  xo <- xo[order(yo)];  yo <- yo[order(yo)]
  cush.a[[i]] <- xc - xo
  cush.ap[[i]] <- wilcox.test(xc,xo,paired=TRUE)$p.value
}
table(round(unlist(cush.ap),3))
test <- names(cush.com)[cush.ap > 0.05]

@ 

\section{Richness Differences Produced by Cushion}

<<>>=
##Use a paired test of the differences in abundances
cush.r <- list()
cush.rp <- list()
for (i in 1:length(cush.com)){
  xc <- apply(cush.com[[i]][cush.micro[[i]] == 'cushion',],1,bin.sum)
  xo <- apply(cush.com[[i]][cush.micro[[i]] == 'open',],1,bin.sum)
  yc <- cush.rep[[i]][cush.micro[[i]] == 'cushion']
  yo <- cush.rep[[i]][cush.micro[[i]] == 'open']  
  xc <- xc[order(yc)];  yc <- yc[order(yc)]
  xo <- xo[order(yo)];  yo <- yo[order(yo)]
  cush.r[[i]] <- xc - xo
  cush.rp[[i]] <- wilcox.test(xc,xo,paired=TRUE)$p.value
}

table(round(unlist(cush.rp),3))
names(cush.com)[cush.rp > 0.05]

@ 


\section{Compositional Differences Produced by Cushions}

<<>>=
##Use a paired test of the community distance inside versus out.
cush.d <- list()
cush.dp <- list()
for (i in 1:length(cush.com)){
  xc <- cush.com[[i]][cush.micro[[i]] == 'cushion',]
  xo <- cush.com[[i]][cush.micro[[i]] == 'open',]
  yc <- cush.rep[[i]][cush.micro[[i]] == 'cushion']
  yo <- cush.rep[[i]][cush.micro[[i]] == 'open']  
  xc <- xc[order(yc),];  yc <- yc[order(yc)]
  xo <- xo[order(yo),];  yo <- yo[order(yo)]
  x <- rbind(xc,xo);y <- c(yc,yo)
  x <- cbind(x,rep(1,nrow(x)))
                                        #  x <- apply(x,2,function(x) x/sum(x))
                                        #  x[is.na(x)] <- 0
  x[x!=0] <- 1 #presence absence data
  d <- vegdist(x)
  d <- as.matrix(d)
  d <- diag(d[cush.micro[[i]] == 'cushion',cush.micro[[i]] == 'open'])
  cush.d[[i]] <- d
  cush.dp[[i]] <- wilcox.test(d,alternative='greater')$p.value
}

table(round(unlist(cush.dp),10))
names(cush.com)[cush.dp > 0.05]

@ 

\section{Community Variance Differences}

<<>>=
##Calculate the sum of the trace from the covariance matrices of cushion and open
cush.t <- list()
cush.tp <- list()
for (i in 1:length(cush.com)){
  xc <- cush.com[[i]][cush.micro[[i]] == 'cushion',]
  xo <- cush.com[[i]][cush.micro[[i]] == 'open',]
  yc <- cush.rep[[i]][cush.micro[[i]] == 'cushion']
  yo <- cush.rep[[i]][cush.micro[[i]] == 'open']  
  xc <- xc[order(yc),];  yc <- yc[order(yc)]
  xo <- xo[order(yo),];  yo <- yo[order(yo)]
  x <- rbind(xc,xo)
  y <- c(yc,yo)
  x <- apply(x,2,function(x) x/sum(x))
  t <- diag(var(t(x)))
  cush.t[[i]] <- sum(t[cush.micro[[i]] == 'cushion']) - sum(t[cush.micro[[i]] == 'open'])
  cush.tp[[i]] <- wilcox.test(t[cush.micro[[i]] == 'cushion'],t[cush.micro[[i]] == 'open'],alternative='great')$p.value
}

hist(unlist(cush.t))
table(round(unlist(cush.tp),10))
nodif.t <- (1:length(cush.com))[cush.tp > 0.05]
                                        #gplot(abs(as.matrix(cush.ind[[nodif.t[1]]][[1]])))
                                        #gplot(abs(as.matrix(cush.ind[[nodif.t[1]]][[2]])))

@ 


\section{Bray-Curtis Dissimilarity Based Partial-Correlations}

<<>>=
    cush.ind <- list()
    cush.ggm <- list()
    along <- 1:length(cush.com)
    for (i in along){
      x <- cush.com[[i]]
      x.in <- x[cush.micro[[i]] == 'cushion',]
      x.out <- x[cush.micro[[i]] == 'open',]
                                        #use Fortuna (Gower) method
      x.in <- x.in[,apply(x.in,2,sum) != 0]
      x.out <- x.out[,apply(x.out,2,sum) != 0]
                                        #relativize by species max
      x.in <- apply(x.in,2,function(x) x/max(x))
      x.in[is.na(x.in)] <- 0
      x.out <- apply(x.out,2,function(x) x/max(x))
      x.out[is.na(x.out)] <- 0
                                        #plot clusters
                                        #plot(hclust(vegdist(t(x.in))))
                                        #in
      d <- as.matrix(vegdist(t(x.in)))
      ind.in <- ind.net(d,nrow(x.in),alpha=0.05,fix.na=TRUE,fix.inf=TRUE)
                                        #out
      d <- as.matrix(vegdist(t(x.out)))
      ind.out <- ind.net(d,nrow(x.out),alpha=0.05,fix.na=TRUE,fix.inf=TRUE)
                                        #Make arrays conform.
      cush.ind[[i]] <- conform(ind.in,ind.out)
      names(cush.ind[[i]]) <- c('cushion','open')
                                        #gene net ggm's
      cush.ggm[[i]] <- conform(ggm.estimate.pcor(x.in),ggm.estimate.pcor(x.out))
    }

names(cush.ind) <- names(cush.com)
names(cush.ggm) <- names(cush.com)
##Look at the correlation between the number of cushions sampled and the degree of the network
                                        #number of cushions sampled (cushion and open are equal)
cush.n <- as.numeric(lapply(cush.micro,function(x) length(x[x == 'open'])))

                                        #separate the indepence networks and calculate the degrees
ind.in <- lapply(cush.ind,function(x) x[[1]])
ind.out <- lapply(cush.ind,function(x) x[[2]])
deg.in <- as.numeric(lapply(ind.in,function(x) length(x[x != 0])))
deg.out <- as.numeric(lapply(ind.out,function(x) length(x[x != 0])))
                                        #plot the patterns of in and out
cor(deg.in,cush.n)
cor(deg.out,cush.n)
plot(cush.n,deg.in,ylim=c(0,max(c(deg.in,deg.out))),pch=19,col='black',ylab='Number of Connections',xlab='Number of Cushions Sampled')
points(cush.n,deg.out,pch=1,col='black')
abline(lm(deg.in~cush.n),lty=2)
abline(lm(deg.out~cush.n),lty=1)
legend('topleft',legend=c('Cushion','Open'),pch=c(19,1))

##Patterns with phylogenetics
                                        #import phylo results from brad
phylo <- read.csv('/Users/Aeolus/Documents/Active_Projects/FacilitationNetworks/GeneticsofFacilitationNetworks/phylo_data/phylo_data_for_Matt.csv')
phylo <- phylo[order(phylo$Sites),]
                                        #Are their patterns in modularity?
                                        #Compute modules
                                        #using the walktrap.community function
                                        #cushion
mod.in <- list()
mod.in <- lapply(ind.in,function(x) getModules(x)[[2]])
nmod.in <- unlist(lapply(mod.in,max))
isol.in <- unlist(lapply(mod.in,function(x) length(x[x == 0])))
                                        #open
mod.out <- list()
mod.out <- lapply(ind.out,function(x) getModules(x)[[2]])
nmod.out <- unlist(lapply(mod.out,max))
isol.out <- unlist(lapply(mod.out,function(x) length(x[x == 0])))
                                        #Modularity
                                        #cushion
m.in <- numeric()
for (i in 1:length(mod.in)){
x <- round(ind.in[[i]],2)
y <- mod.in[[i]]
x <- x[y != 0, y != 0]
y <- y[y != 0]
x <- graph.adjacency(x,weighted=TRUE,mode='undirected')
m.in[[i]] <- modularity(x,y)
}
                                        #open
m.out <- numeric()
for (i in 1:length(mod.out)){
x <- round(ind.out[[i]],2)
y <- mod.out[[i]]
x <- x[y != 0, y != 0]
y <- y[y != 0]
x <- graph.adjacency(x,weighted=TRUE,mode='undirected')
m.out[[i]] <- modularity(x,y)
}
                                        #Make NaN's == 0
m.in[is.na(m.in)] <- 0
m.out[is.na(m.out)] <- 0
                                        #check that the ordering of the data match
all(as.character(phylo$Sites) == cush.site)
cush.nmdif <- nmod.in - nmod.out

@ 

%%Network Centrality
<<>>=
cush.cin <- lapply(cush.ind,function(x) centralization(x[[1]],'degree'))
cush.cout <- lapply(cush.ind,function(x) centralization(x[[2]],'degree'))
cush.cdif <- unlist(cush.cin) - unlist(cush.cout)

@ 


%%Positive versus negative inside versus outside cushions
<<>>=
cush.pos <- lapply(cush.ind,function(x) c(length(x[[1]][x[[1]] > 0]),length(x[[2]][x[[2]] > 0])))
cush.neg <- lapply(cush.ind,function(x) c(length(x[[1]][x[[1]] < 0]),length(x[[2]][x[[2]] < 0])))
cush.mp <- c(mean(unlist(lapply(cush.pos,function(x)x[1]))),mean(unlist(lapply(cush.pos,function(x)x[2])))) #mean number of positives
cush.sp <- c(se(unlist(lapply(cush.pos,function(x)x[1]))),se(unlist(lapply(cush.pos,function(x)x[2])))) #se number of positives
cush.mn <- c(mean(unlist(lapply(cush.neg,function(x)x[1]))),mean(unlist(lapply(cush.neg,function(x)x[2])))) #mean number of negative
cush.sn <- c(se(unlist(lapply(cush.neg,function(x)x[1]))),se(unlist(lapply(cush.neg,function(x)x[2])))) #se number of negative
cush.pp <- wilcox.test(unlist(lapply(cush.pos,function(x)x[1])),unlist(lapply(cush.pos,function(x)x[2])))$p.value
cush.pn <- wilcox.test(unlist(lapply(cush.neg,function(x)x[1])),unlist(lapply(cush.neg,function(x)x[2])))$p.value

par(mfrow=c(1,2))
barplot2(cush.mp,names=c('Cushion','Open'),plot.ci=TRUE,ci.u=cush.mp + cush.sp,ci.l=cush.mp - cush.sp,ylab='Number of Positives')
legend('topright',legend=paste('p = ',round(cush.pp,2)),bty='n',cex=1)
barplot2(cush.mn,names=c('Cushion','Open'),plot.ci=TRUE,ci.u=cush.mn + cush.sn,ci.l=cush.mn - cush.sn,ylab='Number of Negatives')
legend('topright',legend=paste('p = ',round(cush.pn,2)),bty='n',cex=1)

hist(unlist(lapply(cush.pos,function(x) x[1]-x[2])))
hist(unlist(lapply(cush.neg,function(x) x[1]-x[2])))

cush.mud <- unlist(lapply(cush.ind,function(x) mean(x[[1]][upper.tri(x[[1]])])-mean(x[[2]][upper.tri(x[[2]])])))
hist((cush.mud),main='',xlab='Difference in Mean of Networks')
legend('topright',legend=paste('p = ',round(wilcox.test((cush.mud))$p.value,2)),bty='n',cex=1.5)

cush.mud
cush.mui <- unlist(lapply(cush.ind,function(x) mean(x[[1]])))
cush.muo <- unlist(lapply(cush.ind,function(x) mean(x[[2]])))
plot(density(cush.mui),ylim=c(0,50))
lines(density(cush.muo),lty=2)

@ 

%%Distance between cushion-open networks
<<>>=
cush.nd <- as.numeric(lapply(cush.ind,function(x) mDist(x[[1]],x[[2]])))
hist(cush.nd,main='',xlab='Network Distance (Cushion vs Open)')
legend('topright',bty='n',legend='p <<< 0.001')
                                        #legend('topright',bty='n',legend=paste('p = ',wilcox.test(cush.nd)$p.value))
nri.d <- phylo$nri.z.cushion.mean - phylo$nri.z.open.mean
plot(cush.nd~nri.d)
abline(lm(cush.nd~nri.d))
summary(lm(cush.nd~nri.d))
names(cush.ind)[cush.nd > 3]

cush.<- cush.ind[cush.nd == max(cush.nd)]

@ 

%%Is network distance related to the sample size, abundance, richness,
%%variance, composition or nri.dif

<<>>=
n.cush <- unlist(lapply(cush.com,function(x) nrow(x)/2))
nd.pairs <- cbind(n.cush,unlist(lapply(cush.a,mean)),unlist(lapply(cush.r,mean)),unlist(cush.t),unlist(lapply(cush.d,mean)),nri.d,cush.nmdif,cush.cdif,as.numeric(cush.nd))
colnames(nd.pairs) <- c('N Cushions','Mean Dif A','Mean Dif R','Dif Var','Mean Com Dif','Std NRI Dif','Dif N Mod','Dif Centrality','Net Dif')
colnames(nd.pairs) <- sapply(colnames(nd.pairs),function(x) gsub(" ",".",x))
nd.pairs <- na.omit(nd.pairs)
pairs(nd.pairs,diag.panel=panel.hist,lower.panel=panel.smooth,upper.panel=panel.cor,cex.labels=1,cex.cor=5,cex=0.5,pch=20,span=1)
colnames(nd.pairs)

@ 

%%SEM

<<>>=
  model.cush <- specify.model(file='~/GoFN/AlpineSEMmodel.txt') ####
            colnames(nd.pairs)
            sem.data <- nd.pairs[,-4]
            Sigma <- var(sem.data)
            cush.sem <- sem(model.cush,S=Sigma,N=nrow(sem.data))
            summary(cush.sem)
            mod.indices(cush.sem)
            effects(cush.sem)
            sem.std <- cush.sem
            standardizedCoefficients(cush.sem)
            pathDiagram(cush.sem,file='cushSEMpath',edge.labels='values',standardize=TRUE,ignore.double=FALSE,size=c(12,12)) #export to graphviz

@ 


\section{Figures}
\pagebreak
<<fig=true,echo=false,width=11,height=12>>=
i <- (1:length(cush.ind))[cush.nd == max(cush.nd)]
#I'm not sure how negative correlations are recovered though.
test <- cush.com[[i]][cush.micro[[i]] == 'cushion',]
test <- cor(test)
test[is.na(test)] <- 0
test1 <- conform(cush.ind[[i]][[1]],test)[[2]]
test2 <- cush.com[[i]][cush.micro[[i]] == 'open',]
test2 <- cor(test2)
test2[is.na(test2)] <- 0
test2 <- conform(cush.ind[[i]][[2]],test2)[[2]]
#distances for cluster graphs
d1 <- cush.com[[i]][cush.micro[[i]] == 'cushion',]
do <- rep(1,ncol(d1))
d1 <- rbind(d1,do)
d1 <- vegdist(t(d1))
d2 <- cush.com[[i]][cush.micro[[i]] == 'open',]
do <- rep(1,ncol(d2))
d2 <- rbind(d2,do)
d2 <- vegdist(t(d2))
g1 <- getModules(cush.ind[[i]][[1]])
g2 <- getModules(cush.ind[[i]][[2]])
par(mfrow=c(3,2),oma=c(0,0,0,0),mar=c(3.5,2,2,1))
plot(hclust(d1),main='cushion',cex=0.5,sub='',xlab='')
plot(hclust(d2),main='open',cex=0.5,sub='',xlab='')
coord <- gplot(abs(test1),edge.lwd=(abs(test1) + 1)^5,edge.col=pnEdges(test1),vertex.col='grey',vertex.border='darkgrey')
gplot(abs(test2),edge.lwd=(abs(test2) + 1)^5,coord=coord,edge.col=pnEdges(test2),vertex.col='grey',vertex.border='darkgrey')
coord1 <- gplot(abs(g1[[1]]),edge.lwd=(abs(g1[[1]]) + 1)^5,displaylabels=TRUE,edge.col=pnEdges(g1[[1]]),label.cex=0.5,vertex.col='grey',vertex.border='darkgrey')
coord2 <- gplot(abs(g2[[1]]),edge.lwd=(abs(g2[[1]]) + 1)^5,displaylabels=TRUE,edge.col=pnEdges(g2[[1]]),label.cex=0.5,vertex.col='grey',vertex.border='darkgrey')

@ 

\pagebreak
<<fig=true,echo=false,width=11,height=11>>=
par(mfrow=c(2,2))
gplot(abs(g1[[1]]),edge.lwd=(abs(g1[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g1[[1]]),label.cex=0.5,vertex.col='grey',vertex.border='darkgrey',coord=coord1,main='Cushion',vertex.cex=1.5)
gplot(abs(g2[[1]]),edge.lwd=(abs(g2[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g2[[1]]),label.cex=0.5,vertex.col='grey',vertex.border='darkgrey',coord=coord2,main='Open',vertex.cex=1.5)
gplot(abs(g1[[1]]),edge.lwd=(abs(g1[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g1[[1]]),label.cex=0.5,vertex.col=g1[[2]],vertex.border='darkgrey',coord=coord1,vertex.cex=1.5)
gplot(abs(g2[[1]]),edge.lwd=(abs(g2[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g2[[1]]),label.cex=0.5,vertex.col=g2[[2]],vertex.border='darkgrey',coord=coord2,vertex.cex=1.5)

@ 

\pagebreak
<<echo=false,results=hide>>=
par(mfrow=c(1,2))
gplot(abs(g1[[1]]),edge.lwd=(abs(g1[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g1[[1]]),label.cex=0.5,vertex.col=g1[[2]],vertex.border='darkgrey',coord=coord1,vertex.cex=1.5)
gplot(abs(g2[[1]]),edge.lwd=(abs(g2[[1]]) + 1)^5,displaylabels=FALSE,edge.col=pnEdges(g2[[1]]),label.cex=0.5,vertex.col=g2[[2]],vertex.border='darkgrey',coord=coord2,vertex.cex=1.5)

@ 

<<fig=true,echo=false,width=11,height=11>>=
for.pairs <- cbind(cush.n,nmod.in,nmod.out,isol.in,isol.out)
pairs(for.pairs,lower.panel=panel.cor)

@ 


\pagebreak

\section{Tables}

<<echo=false,results=tex>>=
                                        #number of modules
number.modules.cushion <- nmod.in
number.modules.open <- nmod.out
NRI.z.cushion <- phylo$nri.z.cushion.mean
NRI.z.open <- phylo$nri.z.open.mean
xtable(summary(glm(number.modules.cushion~NRI.z.cushion)))
xtable(summary(glm(number.modules.open~NRI.z.open)))
                                        #centralization
centralization.cushion <- unlist(cush.cin)
centralization.open <- unlist(cush.cout)
NRI.z.cushion <- phylo$nri.z.cushion.mean
NRI.z.open <- phylo$nri.z.open.mean
xtable(summary(glm(centralization.cushion~NRI.z.cushion)))
xtable(summary(glm(centralization.open~NRI.z.open)))

@ 

<<>>=
par(mfrow=c(1,1))
plot(cush.nd~nri.d,xlab='NRI Difference (Cushion - Open)',ylab='Network Distance (Cushion - Open)',pch=20,cex=1)
abline(lm(cush.nd~nri.d))
summary(glm(cush.nd~nri.d))
legend('topright',legend='p = 0.0157',bty='n')

@ 

<<fig=true,echo=false,width=11,height=6>>=
par(mfrow=c(2,2))
                                        #number of modules
plot(nmod.in~phylo$nri.z.cushion.mean,xlab='Mean NRI (Cushion)',ylab='Number of Modules')
abline(in.fit <- lm(nmod.in~phylo$nri.z.cushion.mean))
legend('topleft',legend='p = 0.0002',bty='n')
plot(nmod.out~phylo$nri.z.open.mean,xlab='Mean NRI (Open)',ylab='Number of Modules')
abline(out.fit <- lm(nmod.out~phylo$nri.z.open.mean))
legend('topleft',legend='p = 0.8066',bty='n')
                                        #centrality
plot(unlist(cush.cin)~phylo$nri.z.cushion.mean,xlab='Mean NRI (Cushion)',ylab='Centralization')
abline(lm(unlist(cush.cin)~phylo$nri.z.cushion.mean))
legend('topleft',legend='p = 0.0159',bty='n')
plot(unlist(cush.cout)~phylo$nri.z.open.mean,xlab='Mean NRI (Open)',ylab='Number Centralization')
abline(lm(unlist(cush.cout)~phylo$nri.z.open.mean))
legend('topleft',legend='p = 0.7401',bty='n')

@ 


\end{document}  


